### ISSUE TITLE
unlock

### ISSUE THREAD

**Issue by KazuCocoa** [Magic-Pod/AppiumRegressionCheck#10]

**Comment by KazuCocoa** [comment]
I could reproduce with Android 8.0 emulator x Swip unlock.

```
[HTTP] <-- POST /wd/hub/session/46c1c128-5019-4d90-b58a-1bed16169c54/appium/device/lock 200 1055 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/46c1c128-5019-4d90-b58a-1bed16169c54/appium/device/unlock
[HTTP] {"{}":""}
[debug] [W3C] Calling AppiumDriver.unlock() with args: ["46c1c128-5019-4d90-b58a-1bed16169c54"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [ADB] Device API level: 27
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Device API level: 27
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [ADB] Device API level: 27
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Device API level: 27
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[debug] [AndroidDriver] Screen unlocked successfully
[debug] [W3C] Responding to client with driver.unlock() result: null
[HTTP] <-- POST /wd/hub/session/46c1c128-5019-4d90-b58a-1bed16169c54/appium/device/unlock 200 56899 ms - 14
[HTTP]
```

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-android-driver/blob/f5475361722a14d08dab2229ffe085bdb8a34f3e/lib/android-helpers.js#L441

---

Capabilities for locks.
https://github.com/appium/appium-android-driver/blob/9a9ee19a71ba106d5afdfd3d98731881b7571b44/docs/UNLOCK.md

---

https://github.com/appium/appium-android-driver/blob/f5475361722a14d08dab2229ffe085bdb8a34f3e/lib/android-helpers.js#L462
The `adb shell dumpsys window` got unlock but the above line run retry. I guess if we reduce the time and increase the interval, the waiting period will improve.... The timeout is `1 second` x `twice` so far though...

**Comment by KazuCocoa** [comment]
1. adb hung
     - Appium server can't get the result of `adb -P 5037 -s emulator-5554 shell dumpsys window`
     - We should kill the adb server once
2. Retry logic run https://github.com/appium/appium-android-driver/blob/f5475361722a14d08dab2229ffe085bdb8a34f3e/lib/android-helpers.js#L452 but  `await helpers.verifyUnlock(adb);`

---

Sometimes, we can see only force-stop the unlock app. It means the interval is short in the case.

```
[HTTP] --> POST /wd/hub/session/e8a876dc-4f5b-4dd2-83b5-eaa540fddfa1/appium/device/lock
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.lock() with args: [null,"e8a876dc-4f5b-4dd2-83b5-eaa540fddfa1"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[debug] [ADB] Pressing the KEYCODE_POWER button to lock screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell input keyevent 26'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[debug] [W3C] Responding to client with driver.lock() result: null
[HTTP] <-- POST /wd/hub/session/e8a876dc-4f5b-4dd2-83b5-eaa540fddfa1/appium/device/lock 200 6042 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/e8a876dc-4f5b-4dd2-83b5-eaa540fddfa1/appium/device/unlock
[HTTP] {"{}":""}
[debug] [W3C] Calling AppiumDriver.unlock() with args: ["e8a876dc-4f5b-4dd2-83b5-eaa540fddfa1"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[Logcat] Logcat terminated with code 0, signal null
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[AndroidDriver] after unlockWithHelperApp
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[debug] [AndroidDriver] Screen unlocked successfully
[debug] [W3C] Responding to client with driver.unlock() result: null
[HTTP] <-- POST /wd/hub/session/e8a876dc-4f5b-4dd2-83b5-eaa540fddfa1/appium/device/unlock 200 375857 ms - 14
[HTTP]
```

**Comment by KazuCocoa** [comment]
The response of ` io.appium.unlock/.Unlock` looks unstable... Since we insert log between 

https://github.com/appium/appium-android-driver/blob/f5475361722a14d08dab2229ffe085bdb8a34f3e/lib/android-helpers.js#L452-L453 , I wasn't able to see the log...

```
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
```

**Comment by KazuCocoa** [comment]
But https://github.com/appium/unlock_apk/blob/master/src/io/appium/unlock/Unlock.java looks enough...

**Comment by KazuCocoa** [comment]
Unlock app launch very slow..

```
$ /Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=io.appium.unlock/.Unlock }
Status: timeout
Activity: io.appium.unlock/.Unlock
WaitTime: 27059
Complete
```

**Comment by KazuCocoa** [comment]
logcat is:

```
04-29 07:14:08.838 1693-2352/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.appium.unlock/.Unlock} from uid 2000 on display 0
04-29 07:14:09.178 1693-2200/system_process I/ActivityManager: moveTaskToBack: TaskRecord{d04211 #57 A=io.appium.unlock U=0 StackId=1 sz=1}
04-29 07:14:09.494 1693-2328/system_process I/ActivityManager: Activity reported stop, but no longer stopping: ActivityRecord{e9dbf20 u0 io.appium.unlock/.Unlock t57 f}
```

**Comment by KazuCocoa** [comment]
Update: https://github.com/Magic-Pod/AppiumRegressionCheck/issues/10#issuecomment-385228466

1. adb restart
2. don't `await`

**Comment by KazuCocoa** [comment]
The force stop also took much time on emulator..

```
/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock
```

Totally, the emulator's response was slow and so, we should modify some retry, wait and interbal.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-android-driver/compare/master...KazuCocoa:match-better-retry-deprecated-unlock?expand=1

**Comment by KazuCocoa** [comment]
I'd say that is slightly...
It means I found `adb` command hangs sometimes. If if happens, unlock command fails since Appium server can't get any responses from adb command.

**Comment by NozomiIto** [comment]
I've added lock/unlock tests for iOS simulator and Android emulator, and I found these tests work well with Appium1.8.0+your fix for appium_android_driver combination!

**Comment by KazuCocoa** [comment]
hmmm... it's odd.

**Comment by NozomiIto** [comment]
I tried appium@1.8.1-beta1 and appium-android-driver@2.6.0, but situation is the same..

<details>
  <summary>npm modules list</summary>
<pre>
itounozomu-no-MacBook-Pro:~ itonozomi$ npm -g list | grep appium
├─┬ appium@1.8.1-beta1
│ ├─┬ appium-android-driver@2.6.0
│ │ ├─┬ appium-adb@6.9.2
│ │ │ ├── appium-support@2.16.1 deduped
│ │ ├─┬ appium-android-bootstrap@2.10.2
│ │ │ ├── appium-base-driver@2.30.0 deduped
│ │ │ ├── appium-support@2.16.1 deduped
│ │ │ ├─┬ appium-uiautomator@1.2.0
│ │ │ │ ├── appium-adb@6.9.2 deduped
│ │ │ │ ├── appium-support@2.16.1 deduped
│ │ ├── appium-android-ime@2.0.0
│ │ ├── appium-base-driver@2.30.0 deduped
│ │ ├─┬ appium-chromedriver@3.6.0
│ │ │ ├── appium-base-driver@2.30.0 deduped
│ │ │ ├── appium-support@2.16.1 deduped
│ │ ├── appium-support@2.16.1 deduped
│ │ ├── appium-unlock@2.0.0
│ │ ├── io.appium.settings@2.4.0
│ ├─┬ appium-base-driver@2.30.0
│ │ ├── appium-support@2.16.1 deduped
│ ├─┬ appium-espresso-driver@1.0.0-beta.9
│ │ ├── appium-adb@6.9.2 deduped
│ │ ├── appium-android-driver@2.6.0 deduped
│ │ ├── appium-base-driver@2.30.0 deduped
│ │ ├── appium-support@2.16.1 deduped
│ ├─┬ appium-fake-driver@0.4.0
│ │ ├── appium-base-driver@2.30.0 deduped
│ │ ├── appium-support@2.16.1 deduped
│ ├─┬ appium-ios-driver@2.4.1
│ │ ├── appium-base-driver@2.30.0 deduped
│ │ ├─┬ appium-ios-simulator@2.12.1
│ │ │ ├── appium-support@2.16.1 deduped
│ │ │ ├── appium-xcode@3.5.0 deduped
│ │ ├─┬ appium-remote-debugger@3.11.1
│ │ │ ├── appium-base-driver@2.30.0 deduped
│ │ │ ├── appium-support@2.16.1 deduped
│ │ ├── appium-support@2.16.1 deduped
│ │ ├─┬ appium-xcode@3.5.0
│ │ │ ├── appium-support@2.16.1 deduped
│ │ │ ├── appium-support@2.16.1 deduped
│ │ │ ├── appium-xcode@3.5.0 deduped
│ ├─┬ appium-mac-driver@1.2.0
│ │ ├── appium-base-driver@2.30.0 deduped
│ │ ├── appium-support@2.16.1 deduped
│ ├─┬ appium-selendroid-driver@1.8.0
│ │ ├── appium-adb@6.9.2 deduped
│ │ ├── appium-android-driver@2.6.0 deduped
│ │ ├── appium-base-driver@2.30.0 deduped
│ │ ├── appium-support@2.16.1 deduped
│ ├─┬ appium-support@2.16.1
│ ├─┬ appium-uiautomator2-driver@1.12.0
│ │ ├── appium-adb@6.9.2 deduped
│ │ ├── appium-android-driver@2.6.0 deduped
│ │ ├── appium-base-driver@2.30.0 deduped
│ │ ├── appium-support@2.16.1 deduped
│ │ ├── appium-uiautomator2-server@1.10.0
│ ├─┬ appium-windows-driver@1.2.0
│ │ ├── appium-base-driver@2.30.0 deduped
│ │ ├── appium-support@2.16.1 deduped
│ ├─┬ appium-xcuitest-driver@2.79.3
│ │ ├── appium-base-driver@2.30.0 deduped
│ │ ├── appium-ios-driver@2.4.1 deduped
│ │ ├── appium-ios-simulator@2.12.1 deduped
│ │ ├── appium-remote-debugger@3.11.1 deduped
│ │ ├── appium-support@2.16.1 deduped
│ │ ├── appium-xcode@3.5.0 deduped
│ ├─┬ appium-youiengine-driver@1.0.15
│ │ ├── appium-android-driver@2.6.0 deduped
│ │ ├── appium-base-driver@2.30.0 deduped
│ │ ├── appium-ios-driver@2.4.1 deduped
│ │ ├─npm─ appium-mac-driver@1.2.0 deduped
│ │ ├── appium-support@2.16.1 deduped
│ │ ├── appium-xcuitest-driver@2.79.3 deduped
│ │ ├── appium-support@2.16.1 deduped
</pre>
</details>

https://gist.github.com/NozomiIto/069b61b7242ae52d4f89d840104f74da

**Comment by KazuCocoa** [comment]
@NozomiIto 
Unlock looks working since it return `200`. But something happens and it failed to find elements after that, right?

https://github.com/Magic-Pod/AppiumRegressionCheck/issues/10#issuecomment-386868967 and the below is another issue.

```

2018-05-11 13:43:48:912 - info: [debug] [MJSONWP] Responding to client with driver.unlock() result: null
2018-05-11 13:43:48:913 - info: [HTTP] <-- POST /wd/hub/session/4b9e54ed-2c83-4080-90ed-120faefc8506/appium/device/unlock 200 41763 ms - 76
2018-05-11 13:43:48:914 - info: [HTTP] 
2018-05-11 13:43:48:923 - info: [HTTP] --> POST /wd/hub/session/4b9e54ed-2c83-4080-90ed-120faefc8506/elements
2018-05-11 13:43:48:923 - info: [HTTP] {"using":"xpath","value":"//android.widget.FrameLayout[1]"}
2018-05-11 13:43:48:924 - info: [debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//android.widget.FrameLayout[1]","4b9e54ed-2c83-4080-90ed-120faefc8506"]
2018-05-11 13:43:48:926 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-05-11 13:43:48:927 - info: [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-05-11 13:43:48:928 - info: [debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/wd/hub/session/fc9dc776-8b6e-413c-a9ae-d0195916be4c/elements] with body: {"strategy":"xpath","selector":"//android.widget.FrameLayout[1]","context":"","multiple":true}
2018-05-11 13:43:48:950 - error: [MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: read ECONNRESET
2018-05-11 13:43:48:951 - error: [MJSONWP]     at JWProxy.proxy$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:152:13)
2018-05-11 13:43:48:951 - error: [MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2018-05-11 13:43:48:951 - error: [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2018-05-11 13:43:48:951 - error: [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-05-11 13:43:48:952 - error: [MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2018-05-11 13:43:48:952 - error: [MJSONWP]     at <anonymous>
2018-05-11 13:43:48:953 - info: [HTTP] <-- POST /wd/hub/session/4b9e54ed-2c83-4080-90ed-120faefc8506/elements 500 30 ms - 251
2018-05-11 13:43:48:954 - info: [HTTP] 
2018-05-11 13:43:48:970 - info: [HTTP] --> DELETE /wd/hub/session/4b9e54ed-2c83-4080-90ed-120faefc8506
2018-05-11 13:43:48:970 - info: [HTTP] {}
```

**Comment by NozomiIto** [comment]
Thanks for checking.
Yes, unlock succeeds, and finding element after that fails.

> #10 (comment) and the below is another issue.

- Finding failure does not happen when running the same script on Android emulator
- Finding failure also does not happen when commenting out lock and unlock lines and running it on the Android real device.

So I'm afraid lock/unlock commands make the session state invalid.

**Comment by KazuCocoa** [comment]
Can you get the result of `pageSource` after unlocking?

**Comment by NozomiIto** [comment]
I tried the following:

```
console.log("lock");
await driver.lock();
await sleep(1000);
console.log("unlock");
await driver.unlock();
console.log(await driver.source());
```

But driver.source never returns even after 20 minutes.

This is the full server log: https://gist.github.com/NozomiIto/73087139f8d76f41a680efebed6b823b

**Comment by KazuCocoa** [comment]
> 2018-05-11 16:17:38:483 - info: [debug] [UiAutomator2] [UIAutomator2] 
> 2018-05-11 16:17:38:484 - info: [debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:INSTRUMENTATION_RESULT: shortMsg=Process crashed.
> 2018-05-11 16:17:38:484 - info: [debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_CODE: 0

oh.... instrumentation...

**Comment by KazuCocoa** [comment]
> 2018-05-11 16:17:38:484 - info: [debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:INSTRUMENTATION_RESULT: shortMsg=Process crashed.
2018-05-11 16:17:38:484 - info: [debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_CODE: 0
2018-05-11 16:17:56:472 - info: [debug] [ADB] Running '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s ARC7N15C08000180 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'


What about increasing the time of `newCommandTimeout` in capability?

I'm not sure why the instrumentation crash happened. In general, it should work fine only launching other activities like lock application. And in my locale, but emulator btw, works fine.
So, it's another issue with unlock and we should create a new one if this issue happens after appling _increasing the time of `newCommandTimeout` in capability_ for your environment.
@NozomiIto

**Comment by NozomiIto** [comment]
> What about increasing the time of newCommandTimeout in capability?

I increased `newCommandTimeout` to 300, but the result was the same..

> And in my locale, but emulator btw, works fine.

Yes, this problem does not happen on my Android emulator too. This problem is only for the real device (or only for my device).

> And in my locale, but emulator btw, works fine.

OK, I will create the new issue!

**Comment by NozomiIto** [comment]
@KazuCocoa 
I've created another issue https://github.com/Magic-Pod/AppiumRegressionCheck/issues/13 , with `adb logcat` result.
I appreciate if you check it.
