### ISSUE TITLE
Android real device crashes after lock and swipe unlock

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#13]
Related to https://github.com/Magic-Pod/AppiumRegressionCheck/issues/10

[How to reproduce]
- Use appium@1.8.1-beta1 and appium-android-driver@2.6.0
- Rewrite [this line](https://github.com/Magic-Pod/AppiumRegressionCheck/blob/b2af481b94deb193fa6b2bed5d41bc6147fa281b/test/testAppium.js#L182) to `|| caps.platformName == "Android") {` temporarily to run lock/unlock test also for the read device. 
- Connect Android real device which does not have the lock password to PC.
- Run `npm test -- --grep "should work with Android real device with Java8"`
- Then I found lock/unlock worked correctly.
- But finding elements after unlock unexpectedly failed.

**Comment by NozomiIto** [comment]
I also tried the following with newCommandTimeout 300:

```
console.log("lock");
await driver.lock();
await sleep(1000);
console.log("unlock");
await driver.unlock();
console.log(await driver.source());
```

Then, the server log is https://gist.github.com/NozomiIto/827f5a11c000bba9f76316c616555f93 .
(I finally killed the test manually)
`INSTRUMENTATION_RESULT: shortMsg=Process crashed.` seems to be thrown.

And the following it the `adb logcat` result.

https://gist.github.com/NozomiIto/f4940de899ca9606c6a48699064c5105

**Comment by NozomiIto** [comment]
Checking the adb log is very complicated task..

**Comment by KazuCocoa** [comment]
mmm, I ran it with Xperia (tablet, Android 6.0) and it works fine...

```
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
    simpleCheck
screenshot
page source
lock
unlock
find and click
touch action
screenshot again
page source again
      ✓ should work with Android real device with Java8: app=/Users/kazuaki/GitHub/AppiumRegressionCheck/test/../test_app/ApiDemos-debug.apk (85366ms)
kill Appium server
kill Appium server
```

**Comment by KazuCocoa** [comment]
> Checking the adb log is very complicated task..

The latest server and client (JS, Java, Ruby) support websocker based logcat. It's much easier to capture logcat via Appium for a particular period.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-android-driver/blob/ee9dd70205eda6dcfe2b059ec8335f04d9ab5040/test/functional/logs-e2e-specs.js#L43 is an example.

**Comment by KazuCocoa** [comment]
📝 
https://gist.github.com/KazuCocoa/705f251ef5a462d81639fee419d1633a

**Comment by KazuCocoa** [comment]
Let me consider the cause...

**Comment by NozomiIto** [comment]
I think comparing `adb logcat` output on your real device and my device may help the investigation.

**Comment by KazuCocoa** [comment]
> But what is difficult for me is to understand the log contents..

Ah, yeah, it requires Android development knowledges...
Comparing each logcat on my local, I wasn't able to find helpful differences between them...

**Comment by NozomiIto** [comment]
I also can reproduce this problem with the following Nexus 5 API 26 emulator and run test with `AVD_FOR_MAGIC_POD=Nexus_5_API_26 npm test -- --grep "Android emulator"`.

<img width="810" alt="screen shot 2018-05-16 at 17 45 15" src="https://user-images.githubusercontent.com/4276719/40106529-fbfc3c66-5930-11e8-96a2-97fe153a479a.png">

It may be not my real device only problem, but my environment or some kind of timing problem.

**Comment by KazuCocoa** [comment]
hm...
Emulators are easy to hang adb commands but this issue isn't adb command related.
I'll take a look with an emulator you provided.

**Comment by NozomiIto** [comment]
I appreciated that. I hope this emulator setting will reproduce the problem on your machine too.

**Comment by NozomiIto** [comment]
And the following is my adb version information.

<img width="579" alt="screen shot 2018-05-16 at 22 55 45" src="https://user-images.githubusercontent.com/4276719/40121368-605bec8a-595c-11e8-98c9-dcd9d237f391.png">

**Comment by KazuCocoa** [comment]
I tried with https://github.com/Magic-Pod/AppiumRegressionCheck/issues/13#issuecomment-389444254 instance around 10 times. But everything worked fine... The below logs finish a couple minutes.

```
$ APPIUM_MAIN_JS_PATH_FOR_MAGIC_POD=/Users/kazuaki/GitHub/appium/build/lib/main.js AVD8_FOR_MAGIC_POD=Nexus_5_API_26 npm test -- --grep "Android8 emulator"

> appium_regression_check@0.0.1 test /Users/kazuaki/GitHub/AppiumRegressionCheck
> mocha "--grep" "Android8 emulator"



  Appium
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
    simpleCheck
screenshot
page source
lock
unlock
find and click
touch action
package and activity
screenshot again
page source again
```

🤔

**Comment by NozomiIto** [comment]
Still happens even with Appium 1.8.1..

```
screenshot
page source
lock
unlock
close app
launch app
find and click
      1) should work with Android real device with Java8: app=/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../test_app/ApiDemos-debug.apk
kill Appium server
kill Appium server


  0 passing (1m)
  1 failing

  1) Appium simpleCheck should work with Android real device with Java8: app=/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../test_app/ApiDemos-debug.apk:
     Error: [elementByXPathOrNull("//android.widget.FrameLayout[1]")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
      at exports.newError (node_modules/wd/lib/utils.js:148:13)
      at node_modules/wd/lib/callbacks.js:75:19
      at node_modules/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

[server log](https://gist.github.com/NozomiIto/d9c71c7a07ad6c6c22c54e5c9c0eb5f1)

**Comment by NozomiIto** [comment]
https://github.com/appium/appium/issues/10749
https://github.com/appium/appium/issues/10123
https://github.com/appium/appium/issues/10504

They seem to be similar issues.

**Comment by NozomiIto** [comment]
!!!
Based on https://github.com/appium/appium/issues/10749#issuecomment-391868328 , I have restarted my real device, and the problem has been resolved!!
But https://github.com/appium/appium/issues/10749#issuecomment-391868328 also says this problem will happen again after several test runs..

**Comment by KazuCocoa** [comment]
> but next test failed again..

mmm...

**Comment by NozomiIto** [comment]
https://github.com/appium/appium-uiautomator2-driver/pull/174 seems to resolve [a similar problem](https://github.com/appium/appium/issues/10749).
I will try it later.

**Comment by NozomiIto** [comment]
I tried again with appium-uiautomator2-driver 1.13.1, which includes https://github.com/appium/appium-uiautomator2-driver/pull/174, but it still did not fix my problem..
Should I post this issue directly to the appium project?
