### ISSUE TITLE
Appium1.8.1 source command fails with Yahoo transit Android app

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#17]
I think this is the same problem as https://github.com/appium/appium/issues/9934.
This was once fixed, and I'm not sure why this happens again..

## How to reproduce

1. Upgrade Appium server to 1.8.1
2. Install https://play.google.com/store/apps/details?id=jp.co.yahoo.android.apps.transit&hl=ja
3. Temporarily change the test code and use `jp.co.yahoo.android.apps.transit` and `jp.co.yahoo.android.apps.transit.Transit` like the following:

 
<img width="1080" alt="screen shot 2018-06-04 at 17 30 04" src="https://user-images.githubusercontent.com/4276719/40906827-0439c10a-681d-11e8-9a3d-5b8557556519.png">

4. Then run `npm run test -- --grep "should work with Android real device with Java9"`
5. Then getting source fails with the following error:

```
  1) Appium simpleCheck should work with Android real device with Java9: appPackage=jp.co.yahoo.android.apps.transit:
     Error: [source()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: org.w3c.dom.DOMException: android.support.v7.app.ActionBar.ˋ
	at org.apache.harmony.xml.dom.NodeImpl.setNameNS(NodeImpl.java:241)
	at org.apache.harmony.xml.dom.DocumentImpl.renameNode(DocumentImpl.java:318)
	at io.appium.uiautomator2.utils.XMLHierarchy.visitNode(XMLHierarchy.java:122)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:88)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
	at io.appium.uiautomator2.utils.XMLHierarchy.formatXMLInput(XMLHierarchy.java:78)
	at io.appium.uiautomator2.utils.XMLHierarchy.getFormattedXMLDoc(XMLHierarchy.java:60)
	at io.appium.uiautomator2.handler.Source.safeHandle(Source.java:37)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:65)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:247)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:238)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:833)

      at exports.newError (node_modules/wd/lib/utils.js:148:13)
      at node_modules/wd/lib/callbacks.js:75:19
      at node_modules/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```
[server log](https://gist.github.com/NozomiIto/2ffc988b36dd5f6e91742e6a1d8eb64e)

The error happens on the following page.

![transit1](https://user-images.githubusercontent.com/4276719/40907006-6f3f9b1e-681d-11e8-9d90-b4d7ff7bb184.png)

**Comment by NozomiIto** [comment]
Appium1.8.0 also seems to have this problem.

**Comment by KazuCocoa** [comment]
```
error: org.w3c.dom.DOMException: android.support.v7.app.ActionBar.
```

ah...

**Comment by NozomiIto** [comment]
I'm afraid invalid `ˋ` at the end of class name ( ActionBar) causes the problem.
https://github.com/appium/appium/issues/9934 fixed the case for `ˊ`, but `ˋ` is still not escaped..

**Comment by KazuCocoa** [comment]
will fix next release.
cc @NozomiIto
