### ISSUE TITLE
Cannot run Android test with the latest Appium master

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#2]
@KazuCocoa 
When run the Android tests with the command like the following,

`APPIUM_MAIN_JS_PATH_FOR_MAGIC_POD=/Users/itonozomi/Documents/GitHub/appium/build/lib/main.js npm test -- --grep "Android"`

the test will fail with the following Appium server error. 

```2018-03-20 15:49:35:584 - info: [debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_STATUS: Error=Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner} from pid=4041, uid=4041 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server
2018-03-20 15:49:35:584 - info: [debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_STATUS_CODE: -1
2018-03-20 15:49:35:585 - info: [debug] [UiAutomator2] [UIAutomator2] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner} from pid=4041, uid=4041 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server
```

Could you resolve this error?
Whole server log is https://gist.github.com/NozomiIto/baa8b7f91859d3d158a54293e0c479bf .
These Android tests work well at least with Appium1.7.2.

**Comment by KazuCocoa** [comment]
What about uninstall `io.appium.uiautomator2.server.test` and `io.appium.uiautomator2.server` from your test environemt once? @NozomiIto

**Comment by NozomiIto** [comment]
@KazuCocoa 
Thanks, I'll try.
Now this test suite runs both Java8 test and Java9 test, so it may cause some unexpected state.

**Comment by NozomiIto** [comment]
I removed Appium related apps (Appium Settings on Android home screen,  `io.appium.uiautomator2.server.test` and `io.appium.uiautomator2.server`) from my Android device and run only 1 APK test with Java8 with `APPIUM_MAIN_JS_PATH_FOR_MAGIC_POD=/Users/itonozomi/Documents/GitHub/appium/build/lib/main.js npm test -- --grep "ApiDemos-debug.apk"`.

Then most command (like click, screenshot, etc) has succeeded! But quit command still fails..

```
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/wd/lib/utils.js:148:13)
      at PromiseWebdriver.<anonymous> (node_modules/wd/lib/callbacks.js:42:12)
      at cb (node_modules/wd/lib/webdriver.js:165:22)
      at node_modules/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

https://gist.github.com/NozomiIto/283dd1836ff130f856cce1e39d8c2d59 is Appium server log.

**Comment by NozomiIto** [comment]
I removed Appium related apps (Appium Settings on Android home screen,  `io.appium.uiautomator2.server.test` and `io.appium.uiautomator2.server`) from my Android device and run only 1 APK test with Java8 with `APPIUM_MAIN_JS_PATH_FOR_MAGIC_POD=/Users/itonozomi/Documents/GitHub/appium/build/lib/main.js npm test -- --grep " Java8: app=/Users/itonozomi/Documents/GitHub/App"`.

Then the following server error happened. I think this is not APK file related problem
(because it works with Appium1.7.2)

https://gist.github.com/NozomiIto/283dd1836ff130f856cce1e39d8c2d59

**Comment by KazuCocoa** [comment]
I could run test suites in ruby_lib_core with the latest master.
I'll try with this test suite.

```
$ npm list appium-uiautomator2-driver
appium@1.8.0-beta /Users/kazuaki/GitHub/appium
└── appium-uiautomator2-driver@1.5.0
```

**Comment by KazuCocoa** [comment]
- Android 27
    - https://gist.github.com/KazuCocoa/b28cfae10f2e16dd0dc9170813ab105c
- Android 23
    - https://gist.github.com/KazuCocoa/d9de39af98dbe62301b6bd8af3b55a01
    - Reproduced

**Comment by KazuCocoa** [comment]
If we add `appActivity`, it works fine.

```
['app', testAppDir + "/ApiDemos-debug.apk", 'appActivity', 'io.appium.android.apis.ApiDemos'],
```

Reading manifest probably has issues.

**Comment by KazuCocoa** [comment]
Raised https://github.com/appium/appium-adb/blob/3345f9025814a646ccabce778c3e08667448a561/lib/tools/apk-utils.js#L90

**Comment by KazuCocoa** [comment]
From https://github.com/appium/appium-adb/pull/296/files , we start using `apkanalyzer` to handle manifest. I guess the change is affected.

**Comment by KazuCocoa** [comment]
```
$ apkanalyzer -h manifest print test_app/ApiDemos-debug.apk
```

We can get the below XML and it returns `ApiDemos`. The return value is expected one but we need `.ApiDemos` or `io.appium.android.apis.ApiDemos` to detect the launcher activity automatically.

```
        <activity
            android:name="ApiDemos">

            <intent-filter>

                <action
                    android:name="android.intent.action.MAIN" />

                <category
                    android:name="android.intent.category.DEFAULT" />

                <category
                    android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

https://gist.github.com/NozomiIto/283dd1836ff130f856cce1e39d8c2d59#file-appium-server-L48

**Comment by KazuCocoa** [comment]
- With `Appium 1.7.0`

```
[debug] [ADB] badging package: io.appium.android.apis
[debug] [ADB] badging act: io.appium.android.apis.ApiDemos
```

- With master

```
2018-03-20 20:06:57:300 - info: [ADB] Package name: 'io.appium.android.apis'
2018-03-20 20:06:57:300 - info: [ADB] Main activity name: 'ApiDemos'
```

Fix: https://github.com/appium/appium-adb/compare/master...KazuCocoa:fix-autoditection-mainactivity?expand=1

```
2018-03-21 18:18:33:080 - info: [ADB] Package name: 'io.appium.android.apis'
2018-03-21 18:18:33:080 - info: [ADB] Main activity name: 'io.appium.android.apis.ApiDemos'
```

In fixed case, if user change the package name, the detection will be failed. In this case, the user should set full launching activity name by manual in the capability.

**Comment by KazuCocoa** [comment]
📝 I'll create a PR after considering a bit.

**Comment by KazuCocoa** [comment]
cc @NozomiIto

**Comment by KazuCocoa** [comment]
Created a PR

**Comment by NozomiIto** [comment]
Thanks a lot 😄

**Comment by KazuCocoa** [comment]
Another member just fixed the issue in another way.
Try to launch activity directly once and if it fails, the driver tries to launch with `pkg name + '.' + activity name`.

- appium-adb 6.5.0+
- appium-uiautomator2-driver f22d6e9cdc6fa3b1b56eb1a0ac9db8769444ffef (Not released yet)

**Comment by NozomiIto** [comment]
Thanks so much for your quick work! I'll wait for the next appium-uiautomator2-driver release for a while!
