### ISSUE TITLE
Click on iOS real device can fail silently

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#20]
With Appium1.9.0 (and maybe with Appium1.8.0 too), the following test pattern fails on iOS real device. (Maybe does not fail on the simulator)

1. Swipe screen several times by TouchAction so that the "Search Bars" element appears in the bottom of the screen.
2. Wait a few seconds until the screen move has finished.
2. Then click the "Search Bars" element.
3. Unexpectedly the "Search Bars" element is not tapped actually.

If click "Search Bars" 2 times, the tap happens correctly. It seems strange.

### How to reproduce

`npm test -- --grep "moveTo action should work on iOS real"`

You must tweak the press and moveTo parameter of `uiCatalogMoveToTest` method before running test so that "Search Bar" element appears in the bottom of the screen after the swipe.

### Error log

Element "Default" is not found since the page transit by tapping "Search Bar" did not happen..

```
> appium_regression_check@0.0.1 test /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck
> mocha "--grep" "moveTo action should work on iOS real"



  Appium
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
    moveTo action should work
scroll
scroll
      1) on iOS real device
kill Appium server
killed Appium server
kill Appium server
killed Appium server


  0 passing (54s)
  1 failing

  1) Appium
       moveTo action should work
         on iOS real device:
     Error: [elementById("Default")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: An element could not be located on the page using the given search parameters.
      at exports.newError (node_modules/wd/lib/utils.js:149:13)
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/callbacks.js:94:19
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/webdriver.js:185:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)



npm ERR! Test failed.  See above for more details.
```

### Appium server log

https://gist.github.com/NozomiIto/67fa2341b851f421c43122a44aeb34bd

### Movie

I will share you via chat.

**Comment by KazuCocoa** [comment]
> 2018-09-06 18:37:15:100 - info: [debug] [XCUITest] Xcode version set to '9.4.1' (tools v9.4.1.0.1.1528165917)
> 2018-09-06 18:37:15:110 - info: [debug] [XCUITest] iOS SDK Version set to '11.4'

**Comment by KazuCocoa** [comment]
Looks working fine...

```
2018-09-06 18:37:43:044 - info: [HTTP] --> POST /wd/hub/session/cb026b24-f94e-47b0-9fbd-a91cc6864854/touch/perform
2018-09-06 18:37:43:044 - info: [HTTP] {"actions":[{"action":"press","options":{"x":160,"y":284}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":160,"y":142}},{"action":"release","options":{}}]}
2018-09-06 18:37:43:047 - info: [debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":160,"y":284}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":160,"y":142}},{"action":"release","options":{}}],"cb026b24-f94e-47b0-9fbd-a91cc6864854"]
2018-09-06 18:37:43:048 - info: [debug] [XCUITest] Executing command 'performTouch'
2018-09-06 18:37:43:058 - info: [debug] [XCUITest] Received the following touch action: press(options={"x":160,"y":284})-wait(options={"ms":500})-moveTo(options={"x":160,"y":142})-release(options={})
2018-09-06 18:37:43:063 - info: [debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8101/session/F7958CB2-0FD1-4ABF-A02E-852B7E7FF20B/wda/touch/perform] with body: {"actions":[{"action":"press","options":{"x":160,"y":284}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":160,"y":142}},{"action":"release","options":{}}]}
2018-09-06 18:37:44:139 - info: [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"F7958CB2-0FD1-4ABF-A02E-852B7E7FF20B","value":{},"status":0}
2018-09-06 18:37:44:140 - info: [debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
2018-09-06 18:37:44:142 - info: [HTTP] <-- POST /wd/hub/session/cb026b24-f94e-47b0-9fbd-a91cc6864854/touch/perform 200 1097 ms - 74
2018-09-06 18:37:44:142 - info: [HTTP] 
2018-09-06 18:37:45:155 - info: [HTTP] --> POST /wd/hub/session/cb026b24-f94e-47b0-9fbd-a91cc6864854/touch/perform
2018-09-06 18:37:45:155 - info: [HTTP] {"actions":[{"action":"press","options":{"x":160,"y":284}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":160,"y":142}},{"action":"release","options":{}}]}
2018-09-06 18:37:45:156 - info: [debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":160,"y":284}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":160,"y":142}},{"action":"release","options":{}}],"cb026b24-f94e-47b0-9fbd-a91cc6864854"]
2018-09-06 18:37:45:156 - info: [debug] [XCUITest] Executing command 'performTouch'
2018-09-06 18:37:45:159 - info: [debug] [XCUITest] Received the following touch action: press(options={"x":160,"y":284})-wait(options={"ms":500})-moveTo(options={"x":160,"y":142})-release(options={})
2018-09-06 18:37:45:161 - info: [debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8101/session/F7958CB2-0FD1-4ABF-A02E-852B7E7FF20B/wda/touch/perform] with body: {"actions":[{"action":"press","options":{"x":160,"y":284}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":160,"y":142}},{"action":"release","options":{}}]}
2018-09-06 18:37:46:250 - info: [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"F7958CB2-0FD1-4ABF-A02E-852B7E7FF20B","value":{},"status":0}
2018-09-06 18:37:46:251 - info: [debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
2018-09-06 18:37:46:252 - info: [HTTP] <-- POST /wd/hub/session/cb026b24-f94e-47b0-9fbd-a91cc6864854/touch/perform 200 1097 ms - 74
2018-09-06 18:37:46:253 - info: [HTTP] 
2018-09-06 18:37:50:265 - info: [HTTP] --> POST /wd/hub/session/cb026b24-f94e-47b0-9fbd-a91cc6864854/element
2018-09-06 18:37:50:265 - info: [HTTP] {"using":"id","value":"Search Bars"}
2018-09-06 18:37:50:266 - info: [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","Search Bars","cb026b24-f94e-47b0-9fbd-a91cc6864854"]
2018-09-06 18:37:50:266 - info: [debug] [XCUITest] Executing command 'findElement'
```

**Comment by NozomiIto** [comment]
Thanks for you checking.
Yes, it does not happen on the simulator. It  happens only on the real device.

**Comment by KazuCocoa** [comment]
Tried with 12.0, but everything was fine. (5 times)

Will find 11.4 device and try

**Comment by NozomiIto** [comment]
Thanks.

> You must tweak the press and moveTo parameter of uiCatalogMoveToTest method before running > test so that "Search Bar" element appears in the bottom of the screen after the swipe.

Changing this parameter is very important.  If I change this parameter, the problem won't happen on my device too (iOS10.3 iPhone5 real device). The element must appear in the bottom of the screen after swipe like the movie I had shared.

**Comment by NozomiIto** [comment]
@KazuCocoa Since this is maybe iOS10.3 issue, we don't need to fix this problem anymore. (#22)
Thank you!

**Comment by KazuCocoa** [comment]
ah, i see. Thanks
