### ISSUE TITLE
com.google.android.apps.maps test does not work with Appium1.9.1

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#21]
I tried `npm test -- --grep "should work with Android real device with Java9: appPackage=com.google.android.apps.maps"` many times with Appium1.9.1, but it always fails..

- I've uninstalled all appium related apps from my Android real device, but the result was the same.
- I've restarted my device, but the result was the same.

Client log:

```
     Error: [init({"platformName":"Android","deviceName":"Android","automationName":"uiautomator2","udid":"ARC7N15C08000180","appWaitActivity":"*","appPackage":"com.google.android.apps.maps","appActivity":"com.google.android.maps.MapsActivity"})] The environment you requested was unavailable.
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s ARC7N15C08000180 pull '/data/app/com.google.android.apps.maps-1/base.apk
package:/data/app/com.google.android.apps.maps-1/split_config.en.apk' /var/folders/5j/86p6_7p53x92gs6w30cxy3_w0000gn/T/com.google.android.apps.maps.apk' exited with code 1'; Stderr: ''; Code: '1'
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/webdriver.js:140:15
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

Server log: https://gist.github.com/NozomiIto/baf56526e467849b651df3254b2feba6

**Comment by KazuCocoa** [comment]
It should be fixed by https://github.com/appium/appium-android-driver/pull/430

**Comment by KazuCocoa** [comment]
@NozomiIto You can ensure the fix with `appium@beta` version

**Comment by NozomiIto** [comment]
Worked with the latest version. Thanks!
