### ISSUE TITLE
Parallel Appium server run can cause unexpected webDriverAgent installation failure

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#25]
## How to reproduce

`npm run test -- --grep "parallel Appium server run should work"` with Appium1.10.0.
The error sometimes happens. It seems to happen when the initial WebDriverAgent app build takes much time.

## Error log

```

> appium_regression_check@0.0.1 test /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck
> mocha "--grep" "parallel Appium server run should work"



  Appium
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
    parallel Appium server run should work
screenshot
page source
find and click
{"message":"[quit()] Unexpected data in simpleCallback.","data":"The URL '/wd/hub/session' did not map to a valid resource"}
      1) on iOS simulator12
kill Appium server
killed Appium server
kill Appium server
killed Appium server


  0 passing (8m)
  1 failing

  1) Appium
       parallel Appium server run should work
         on iOS simulator12:
     Error: [init({"platformName":"iOS","platformVersion":"12.1","deviceName":"iPhone 8","automationName":"XCUITest","showXcodeLog":false,"useJSONSource":true,"wdaLocalPort":8102,"language":"ja","derivedDataPath":"/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../DerivedData1","fullReset":true,"isHeadless":true,"app":"/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../test_app/magic_pod_demo_app.app"})] The environment you requested was unavailable.
An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8102
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/webdriver.js:138:15
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

## Appium server log for failure

https://gist.github.com/NozomiIto/12dc31c37dbba3f58e8ba356f169d492

## XCode log for failure

/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/DerivedData1/Logs/Test/Test-WebDriverAgentRunner-2019.01.05_18-35-47-+0900.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-B14F3736-73D4-4B79-ABD8-C46CC3DA2B79/WebDriverAgentRunner-CE426F1D-21BD-4B0C-A1D0-E754BA977B34/Session-WebDriverAgentRunner-2019-01-05_183552-I0TAAY.log

https://gist.github.com/NozomiIto/73c35a0f8969d085b0f3e306147a6531

**Comment by KazuCocoa** [comment]
@NozomiIto 
Can you try https://github.com/KazuCocoa/appium-xcuitest-driver/tree/tmp-error-code-35-wda ?
I have not reproduced on my env yet.

If the error happens, `Error Domain=MIInstallerErrorDomain Code=35` appears in your appium log so you can observe the flow.

I'll continue trying to reproduce it on my env.

**Comment by NozomiIto** [comment]
@KazuCocoa 
Thanks! I tried your code but could not catch the error.
According to https://gist.github.com/NozomiIto/73c35a0f8969d085b0f3e306147a6531, the error is maybe `Error Domain=IXUserPresentableErrorDomain Code=1` or `IDETestOperationsObserverErrorDomain Code=4`, but you seems to try to catch different error code and message.

**Comment by KazuCocoa** [comment]
mm

Code=35 should be included in the message. let me relax the catch word to appear the message in appium log

> 18:35:54.069 xcodebuild[54562:1687277] 578CE2BB-6015-4C76-804E-FB470FAAB57E: Failed to install app at path: /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/DerivedData1/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app and options: (null) (error = Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." UserInfo={NSLocalizedFailureReason=Failed to load Info.plist from bundle at path /Users/itonozomi/Library/Developer/CoreSimulator/Devices/578CE2BB-6015-4C76-804E-FB470FAAB57E/data/Library/Caches/com.apple.mobile.installd.staging/temp.30VayU/extracted/Payload/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fa164083e60 {Error Domain=MIInstallerErrorDomain Code=35 "Failed to load Info.plist from bundle at path /Users/itonozomi/Library/Developer/CoreSimulator/Devices/578CE2BB-6015-4C76-804E-FB470FAAB57E/data/Library/Caches/com.apple.mobile.installd.staging/temp.30VayU/extracted/Payload/WebDriverAgentRunner-Runner.app" UserInfo={LegacyErrorString=PackageInspectionFailed, FunctionName=-[MIBundle _validateWithError:], SourceFileLine=38, NSLocalizedDescription=Failed to load Info.plist from bundle at path /Users/itonozomi/Library/Developer/CoreSimulator/Devices/578CE2BB-6015-4C76-804E-FB470FAAB57E/data/Library/Caches/com.apple.mobile.installd.staging/temp.30VayU/extracted/Payload/WebDriverAgentRunner-Runner.app}}, NSLocalizedRecoverySuggestion=Failed to load Info.plist from bundle at path /Users/itonozomi/Library/Developer/CoreSimulator/Devices/578CE2BB-6015-4C76-804E-FB470FAAB57E/data/Library/Caches/com.apple.mobile.installd.staging/temp.30VayU/extracted/Payload/WebDriverAgentRunner-Runner.app, NSLocalizedDescription=This app could not be installed at this time.})

**Comment by NozomiIto** [comment]
Xcode log this time

https://gist.github.com/NozomiIto/56e6e700d047d24a61f33532f281e7d1

/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/DerivedData2/Logs/Test/Test-WebDriverAgentRunner-2019.01.06_12-01-01-+0900.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-5F2A1BF6-6C22-4F92-8DC8-3F848E9C1209/WebDriverAgentRunner-3B31CAF7-BCF1-44ED-B3C2-DACC2F9164E2/Session-WebDriverAgentRunner-2019-01-06_120103-fourNr.log

**Comment by KazuCocoa** [comment]
Code=1 is generic message, according to https://forums.developer.apple.com/thread/81452

Will change to catch the message

**Comment by NozomiIto** [comment]
@KazuCocoa 
I still encounter the error (although I think I reflect your latest change to my Appium)

- Now I use appium master logic plus your code.
- Now I enabled `showXcodeLog`, and you can see more detailed messages in https://gist.github.com/NozomiIto/4adec6f06a18e3fae75a22635b46ec71

**Comment by KazuCocoa** [comment]
Is the gist a part of the full log? (Maybe, your log is too big to attach in gist)

**Comment by NozomiIto** [comment]
You can see the full log by clicking this link on the gist page.

<img width="436" alt="screen shot 2019-01-06 at 16 03 14" src="https://user-images.githubusercontent.com/4276719/50733197-a02fd280-11cc-11e9-8660-5bb34feeae04.png">

**Comment by NozomiIto** [comment]
(I think this message should be located on the last line of gist. Such messages on the top line can be easily missed)

**Comment by NozomiIto** [comment]
> (although I think I reflect your latest change to my Appium)

I confirmed it was surely reflected by adding a small log message by myself.

> I changed a bit to raise an error. Could you take a log again?

OK!

**Comment by NozomiIto** [comment]
> It hasn't happened in my env yet...

You may encounter this problem more easily by increasing parallel Appium server count from 2 to 3, but I'm not sure..

**Comment by NozomiIto** [comment]
@KazuCocoa 

Can I ignore this WebDriverAgent submodule commit number change?

<img width="1233" alt="screen shot 2019-01-06 at 16 41 19" src="https://user-images.githubusercontent.com/4276719/50733498-fce1bc00-11d1-11e9-9345-181153fc9eb5.png">

**Comment by NozomiIto** [comment]
The latest log

https://gist.github.com/NozomiIto/777ed5fedf6ff7551360f2977cf95dc1

**Comment by KazuCocoa** [comment]
ah, yes, sorry. > submodule

**Comment by KazuCocoa** [comment]
Can you try and gapture log again?
`showXcodeLog=false` is prefered in order to restrict log message.

https://github.com/appium/appium-xcuitest-driver/compare/master...KazuCocoa:tmp-error-code-35-wda?expand=1

**Comment by KazuCocoa** [comment]
Since I could reproduce it only once, so far...

**Comment by NozomiIto** [comment]
Next time, the test failed for `showXCodeLog = false`. Appium logs are:

- [appiumServer_Java1.8.log](https://gist.github.com/NozomiIto/6dc76ae77ccf087137d4804230caf8fb)
- [appiumServer_Java9.log](https://gist.github.com/NozomiIto/3f28d4438df428e40170d4373c336d3a) ( No error found)

**Comment by NozomiIto** [comment]
Sorry, https://github.com/appium/appium-xcuitest-driver/commit/d33c266e1919eecd51e61687b2315eed43d3cd83 was not reflected for the above logs.

**Comment by KazuCocoa** [comment]
👍 
i could get a log based on my the latest code

**Comment by NozomiIto** [comment]
Latest log for https://github.com/appium/appium-xcuitest-driver/commit/d33c266e1919eecd51e61687b2315eed43d3cd83:

- [appiumServer_Java1.8.log](https://gist.github.com/NozomiIto/450b21f493ae2d75f997c82ac4aac3df)
- [appiumServer_Java9.log](https://gist.github.com/NozomiIto/9c82fb8234d4349825eddaa02e0cee34)

Test was failed.

```
  1) Appium
       parallel Appium server run should work
         on iOS simulator12:
     Error: [init({"platformName":"iOS","platformVersion":"12.1","deviceName":"iPhone 8","automationName":"XCUITest","showXcodeLog":false,"useJSONSource":true,"wdaLocalPort":8102,"language":"ja","derivedDataPath":"/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../DerivedData1","fullReset":true,"isHeadless":true,"app":"/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../test_app/magic_pod_demo_app.app"})] The environment you requested was unavailable.
An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8102
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/webdriver.js:138:15
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by KazuCocoa** [comment]
I am tweaking where is the best to catch the error and remove cache directory before the next retry.

Defaults to retry https://github.com/appium/appium-xcuitest-driver/blob/83896699be26448ebc12fe463f5b4db85609f895/lib/driver.js#L489 twice.
I am thnking catch the error her. If the error is this, we remove cache before the next retry.

**Comment by NozomiIto** [comment]
https://github.com/Magic-Pod/AppiumRegressionCheck/issues/25#issuecomment-451746999 <= Sorry, this was not run with your fix. I mistakenly used the Appium server without fix.

**Comment by NozomiIto** [comment]
@KazuCocoa 

Test failed with the latest change. Logs are:

- [appiumServer_Java1.8.log](https://gist.github.com/NozomiIto/78b92a048228793aae016651bf3d0dd2)
- [appiumServer_Java9.log](https://gist.github.com/NozomiIto/b96561c2220623084ea9ed5a50e4db64)

**Comment by KazuCocoa** [comment]
```
  1) Appium
       parallel Appium server run should work
         on iOS simulator12:
     Error: [init({"platformName":"iOS","platformVersion":"12.1","deviceName":"iPhone X","automationName":"XCUITest","showXcodeLog":false,"useJSONSource":true,"wdaLocalPort":8104,"language":"ja","derivedDataPath":"/Users/kazuaki/GitHub/AppiumRegressionCheck/test/../DerivedData3","fullReset":true,"isHeadless":true,"app":"/Users/kazuaki/GitHub/AppiumRegressionCheck/test/../test_app/magic_pod_demo_app.app"})] The environment you requested was unavailable.
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, rename '/var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/201907-39911-1hu0iy0.yemf/com.apple.mobile.installd.staging' -> '/Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging'".
      at /Users/kazuaki/GitHub/AppiumRegressionCheck/node_modules/wd/lib/webdriver.js:138:15
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1092:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

🤔 new error message...

``

2019-01-07 13:58:46:336 [Xcode] 2019-01-07 13:58:46.336 xcodebuild[41936:506163] Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." UserInfo={NSLocalizedFailureReason=Failed to create temporary staging dir in /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging, NSUnderlyingError=0x7f825f7d5fc0 {Error Domain=MIInstallerErrorDomain Code=105 "Failed to create temporary staging dir in /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging" UserInfo={NSLocalizedDescription=Failed to create temporary staging dir in /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging, FunctionName=-[MobileInstallationHelperService stageItemAtURL:options:completion:], SourceFileLine=347, NSUnderlyingError=0x7f8260027080 {Error Domain=MIInstallerErrorDomain Code=4 "Failed to create temp dir at path /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging/temp.N7ul4e" UserInfo={PathArgument=file:///Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging/temp.XXXXXX/, NSUnderlyingError=0x7f8260026f70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}, FunctionName=-[MIFileManager createTemporaryDirectoryInDirectoryURL:error:], SourceFileLine=321, NSLocalizedDescription=Failed to create temp dir at path /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging/temp.N7ul4e}}}}, NSLocalizedRecoverySuggestion=Failed to create temporary staging dir in /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging, NSLocalizedDescription=This app could not be installed at this time.}
2019-01-07 13:58:46:337 [Xcode] 
2019-01-07 13:58:46:337 [Xcode] 2019-01-07 13:58:46.336 xcodebuild[41936:506163] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to install or launch the test runner" UserInfo={NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/kazuaki/GitHub/AppiumRegressionCheck/DerivedData3/Logs/Test/Test-WebDriverAgentRunner-2019.01.07_13-58-35-+0900.xcresult, NSLocalizedDescription=Failed to install or launch the test runner, NSUnderlyingError=0x7f825f851fd0 {Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." UserInfo={NSLocalizedFailureReason=Failed to create temporary staging dir in /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging, NSUnderlyingError=0x7f825f7d5fc0 {Error Domain=MIInstallerErrorDomain Code=105 "Failed to create temporary staging dir in /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging" UserInfo={NSLocalizedDescription=Failed to create temporary staging dir in /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging, FunctionName=-[MobileInstallationHelperService stageItemAtURL:options:completion:], SourceFileLine=347, NSUnderlyingError=0x7f8260027080 {Error Domain=MIInstallerErrorDomain Code=4 "Failed to create temp dir at path /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging/temp.N7ul4e" UserInfo=0x7f825fc9b5f0 (not displayed)}}}, NSLocalizedRecoverySuggestion=Failed to create temporary staging dir in /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging, NSLocalizedDescription=This app could not be installed at this time.}}}
2019-01-07 13:58:46:337 [Xcode] 
2019-01-07 13:58:46:346 [Xcode] 
2019-01-07 13:58:46:346 [Xcode] Testing failed:
2019-01-07 13:58:46:346 [Xcode] 	WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: This app could not be installed at this time. Failed to create temporary staging dir in /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging. (Underlying error: Failed to create temporary staging dir in /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging. (Underlying error: Failed to create temp dir at path /Users/kazuaki/Library/Developer/CoreSimulator/Devices/ECEDA200-9325-4E7A-9AF8-E63A2903E5A9/data/Library/Caches/com.apple.mobile.installd.staging/temp.N7ul4e. (Underlying error: The operation couldn’t be completed. No such file or directory)))))
2019-01-07 13:58:46:347 [Xcode] ** TEST EXECUTE FAILED **
2019-01-07 13:58:46:347 [Xcode] 
2019-01-07 13:58:46:347 [Xcode] 
2019-01-07 13:58:46:347 [Xcode] Testing started on 'iPhone X'
```

**Comment by KazuCocoa** [comment]
Tried to disable clearing cache before: https://github.com/appium/appium-xcuitest-driver/pull/838/files
(Closed without merging that though)

**Comment by KazuCocoa** [comment]
https://github.com/KazuCocoa/appium-xcuitest-driver/commit/9d1f83c7ec6d291ea983d65e2ca800656456c5d8

```
2019-01-07 14:33:43:786 [XCUITest] xcodebuild exited with code '65' and signal 'null'
2019-01-07 14:33:43:786 [XCUITest] rejected because of Error Domain=MIInstallerErrorDomain Code=35
2019-01-07 14:33:43:823 [XCUITest] error in webdriveragent.js======: Error Domain=MIInstallerErrorDomain Code=35
2019-01-07 14:33:43:824 [XCUITest] clean....
2019-01-07 14:33:43:824 [XCUITest] installdCacheRoot: /Users/kazuaki/Library/Developer/CoreSimulator/Devices/9850350C-0578-430F-90C9-98E96651FE99/data/Library/Caches/com.apple.mobile.installd.staging
2019-01-07 14:33:43:826 [XCUITest] cleaning...
2019-01-07 14:33:43:826 [XCUITest] tmpRoot: /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/201907-42699-1u40vmq.hr1c
2019-01-07 14:33:43:828 [XCUITest] Launching WebDriverAgent on the device
2019-01-07 14:33:43:829 [XCUITest] Carthage found: '/usr/local/bin/carthage'
```

**Comment by KazuCocoa** [comment]
^ happens if we delete `installdCacheRoot` before re-call `this.xcodebuild.start();`
We probably need to change  re-building?...

**Comment by KazuCocoa** [comment]
BTW, is this happening on non IOS12 simulators?
Will take a look at this later.

**Comment by KazuCocoa** [comment]
I tried with iOS 11.4 three in the same condition on my locale. But I haven't reproduced it yet.
Is this happen only iOS 12? 📝

**Comment by NozomiIto** [comment]
OK, I will also try for iOS11.4 simulators.

**Comment by NozomiIto** [comment]
With iOS11.4 the test passed at least once.
With other problem, I could not try 11.4 test many times..

**Comment by KazuCocoa** [comment]
@NozomiIto 
Can you try out with https://github.com/KazuCocoa/WebDriverAgent/tree/add-product-name x iOS12.0 ?

https://twitter.com/Shashikant86/status/1087260222027190272 advised me about the new build system. I found we must specify some plist stuff in the new build system.
https://medium.com/xcblog/five-things-you-must-know-about-xcode-10-new-build-system-41676cd5fd6c

In the working branch, I specified `PRODUCT_NAME` as `WebDriverAgent`, since I could see a couple of articles addressed `PRODUCT_NAME` to fix Xcode 10 build issue.

You can:

1. just clone the latest
2. go to appium/node_modules/appium-xcuitest-driver/WebDriverAgent
3. replace the agent to the branch
4. Go ahead =3

**Comment by NozomiIto** [comment]
Thanks! I tried you change with Appium1.10.1 freshly installed by npm, but still the following error happens...

https://gist.github.com/NozomiIto/4f732178e628b35b2697c2b24082dbed

```
Failed to load Info.plist from bundle at path /Users/itonozomi/Library/Developer/CoreSimulator/Devices/578CE2BB-6015-4C76-804E-FB470FAAB57E/data/Library/Caches/com.apple.mobile.installd.staging/temp.rGbrlx/extracted/Payload/WebDriverAgentRunner-Runner.app
```

**Comment by KazuCocoa** [comment]
Thanks.
What about below?
You can use vanilla WDA. So, once remove `node_modules/appium-xcuitest-driver` and get https://github.com/KazuCocoa/appium-xcuitest-driver/tree/run-with-legacy-build .

I enabled legacy code build. If the issue never happens with the legacy build, the root cause is probably the new build system.

**Comment by NozomiIto** [comment]
I tried.

- Check out https://github.com/KazuCocoa/appium-xcuitest-driver/tree/run-with-legacy-build and `npm install` and `npm rebuild`
- Rewrite `node_modules/appium-xcuitest-driver` under appium1.10.1 npm module with your appium-xcuitest-driver
- Run the test

I can't find the correct reason, but it failed..

- [appiumServer_Java1.8.log](https://gist.github.com/NozomiIto/9962be122ff7bbb83ea1936d7e0f8247)
- [appiumServer_Java9.log](https://gist.github.com/NozomiIto/156edcd6e29d4e6db7b199ffd8a66341)

**Comment by KazuCocoa** [comment]
The error was very strange, since KissXML has been deleted.
Could you remove Carthage cache and make sure your `node_modules/appium-xcuitest-driver/WebDriverAgent`?

```
m -rf ~/Library/Caches/org.carthage.CarthageKit 
rm -rf ~/Library/Caches/carthage
```

**Comment by KazuCocoa** [comment]
I could build the branch correctly

**Comment by KazuCocoa** [comment]
Is there KissXML in `node_modules/appium-xcuitest-driver/WebDriverAgent/Cartfile.resolved` ?

if yes, your WDA is old version there

**Comment by NozomiIto** [comment]
Ah, yes..

```
github "marekcirkos/KissXML" "5.0.5"
github "marekcirkos/RoutingHTTPServer" "v1.0.1"
github "marekcirkos/peertalk" "v1.0"
```

**Comment by NozomiIto** [comment]
After resolving https://github.com/Magic-Pod/AppiumRegressionCheck/issues/25#issuecomment-456849577, I encountered another error...

https://gist.github.com/NozomiIto/027a43a1ee66a67fbde15a1c3eaa5bbd
Maybe some kind of mismatch between appium1.10.1 and https://github.com/KazuCocoa/appium-xcuitest-driver/tree/run-with-legacy-build and https://github.com/appium/WebDriverAgent/tree/a6c7f38c59a8b18f89c23ce4dd9777dfc272e1e8 , but quite difficult to identify the cause for me..

**Comment by KazuCocoa** [comment]
Difference is only https://github.com/appium/appium-xcuitest-driver/compare/master...KazuCocoa:run-with-legacy-build?expand=1 .
And there is no breaking changes between 1.10.1 and current master (will be 1.11).

mmm
I also face similar build error recently. Basically, that is resolve rependencies error in xcode.
mmm..

```
2019-01-25 20:41:23:946 [Xcode] 
2019-01-25 20:41:23:947 [Xcode] Testing failed:
2019-01-25 20:41:23:947 [Xcode] 
2019-01-25 20:41:23:947 [Xcode] 	'CocoaAsyncSocket/CocoaAsyncSocket.h' file not found
2019-01-25 20:41:23:947 [Xcode] 	WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Cannot launch simulated executable: no file found at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/DerivedData1/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app))
2019-01-25 20:41:23:947 [Xcode] ** TEST EXECUTE FAILED **
2019-01-25 20:41:23:948 [Xcode] 
2019-01-25 20:41:23:948 [Xcode] 
```

**Comment by KazuCocoa** [comment]
In my case, newer build system. So, the error is not only for legacy build one

**Comment by KazuCocoa** [comment]
the error happened on Xcode as well...
mm..

**Comment by NozomiIto** [comment]
This ECONNREFUSED error still happens for iOS12.2 simulator + Xcode11.0 + Appium1.15.0-rc4.
Sometimes this test passes, sometimes not.

- [Log 1](https://gist.githubusercontent.com/NozomiIto/78f0ad3a14c42f92a11290f863929c2c/raw/76b805f950abf413baa5d63e21ba9b450a52011b/appiumServer_Java1.8.log)
- [Log 2](https://gist.githubusercontent.com/NozomiIto/61211fdaadd78e2080dfe3c5fb49fdd8/raw/7f16a2f318ae97c108965b36025467f6dde9f473/appiumServer_Java9.log)
