### ISSUE TITLE
Consecutive Appium server launches always cause socket hangup error with Appium1.15.0

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#26]
- Happens with Apium1.15.0 + iOS real device 12.4 + Xcode 10.3.
- Confirmed this does not happen with Appium1.14.2 + iOS real device 12.4 + Xcode 10.3. 
- Success and failure happen alternately for the same test..
## How to reproduce:

```
npm test -- --grep "should work with iOS real device: app"; npm test -- --grep "should work with iOS real device: app"
```

This does, start server => run test => kill server => start server(but fails) => run test => kill server

## Log

```
nozomi-ito001:AppiumRegressionCheck itonozomi$ npm test -- --grep "should work with iOS real device: app"; npm test -- --grep "should work with iOS real device: app"

> appium_regression_check@0.0.1 test /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck
> mocha "--grep" "should work with iOS real device: app"



  Appium
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
    simpleCheck
screenshot
page source
close app
launch app
find and click
touch action
screenshot again
page source again
      ✓ should work with iOS real device: app=/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../test_app/TestApp.ipa (41493ms)
kill Appium server
killed Appium server
kill Appium server
killed Appium server


  1 passing (57s)


> appium_regression_check@0.0.1 test /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck
> mocha "--grep" "should work with iOS real device: app"



  Appium
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
    simpleCheck
{"message":"[quit()] Unexpected data in simpleCallback.","data":"The URL '/wd/hub/session' did not map to a valid resource"}
      1) should work with iOS real device: app=/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../test_app/TestApp.ipa
(node:19853) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
kill Appium server
killed Appium server
kill Appium server
killed Appium server


  0 passing (36s)
  1 failing

  1) Appium
       simpleCheck
         should work with iOS real device: app=/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../test_app/TestApp.ipa:
     Error: [init({"platformName":"iOS","platformVersion":"9.9","deviceName":"real device","udid":"auto","automationName":"XCUITest","showXcodeLog":true,"useJSONSource":true,"xcodeSigningId":"iPhone Developer","xcodeOrgId":"9U4PT397Q4","wdaLocalPort":8101,"app":"/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../test_app/TestApp.ipa"})] The environment you requested was unavailable.
An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/webdriver.js:149:15
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:448:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:448:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at IncomingMessage.EventEmitter.emit (domain.js:448:20)
      at endReadableNT (_stream_readable.js:1129:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)



npm ERR! Test failed.  See above for more details.
```

## First test run succeeds

[Appium1.15.0 success](https://gist.githubusercontent.com/NozomiIto/d504cadc606f14e2f26a2d96e55fe59f/raw/03966bad6d1eb930cbe3ba53709c0a2bfd0a72ad/gistfile1.txt)

## But second test run fails
[Appium1.15.0 failure](https://gist.github.com/NozomiIto/f3f170fd909abda4db45d0c10228ce6e)

**Comment by KazuCocoa** [comment]
Worked on my env with iOS 13 x Xcode 11.
mm

**Comment by KazuCocoa** [comment]
```
 Appium
launch Appium server with JAVA_HOME=/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home
launch Appium server with JAVA_HOME=/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home
    simpleCheck
screenshot
page source
close app
launch app
find and click
touch action
screenshot again
page source again
      ✓ should work with iOS real device: app=/Users/kazu/GitHub/AppiumRegressionCheck/test/../test_app/TestApp.ipa (53821ms)
kill Appium server
killed Appium server
kill Appium server
killed Appium server


  1 passing (1m)


> appium_regression_check@0.0.1 test /Users/kazu/GitHub/AppiumRegressionCheck
> mocha "--grep" "should work with iOS real device: app"



  Appium
launch Appium server with JAVA_HOME=/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home
launch Appium server with JAVA_HOME=/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home
    simpleCheck
screenshot
page source
close app
launch app
find and click
touch action
screenshot again
page source again
      ✓ should work with iOS real device: app=/Users/kazu/GitHub/AppiumRegressionCheck/test/../test_app/TestApp.ipa (93121ms)
kill Appium server
killed Appium server
kill Appium server
killed Appium server


  1 passing (2m)
```

**Comment by KazuCocoa** [comment]
'Apium1.15.0 + iOS real device 12.4 (iPod Touch) + Xcode 10.3'  worked.
The test app was not valid for the device (since we must re-build with the new cert) so I tested simply call start_driver multiply.
Then, it worked fine.

mmm

**Comment by KazuCocoa** [comment]
```
2019-09-28 15:06:35:504 [IOSDeviceLog] Sep 28 15:06:35 itounozomunoiPad assertiond[58] <Notice>: [WebDriverAgentR:3018] dump assertions count:1 HWM:3 (CPUMON check): {
2019-09-28 15:06:35:504 [IOSDeviceLog]     <BKProcessAssertion: 0x10080ec50; "Developer testing" (backgroundUI:inf); id:\M-b\M^@\M-&23F46420AEAA> [active]
2019-09-28 15:06:35:504 [IOSDeviceLog] }
2019-09-28 15:06:35:504 [IOSDeviceLog] Sep 28 15:06:35 itounozomunoiPad assertiond[58] <Error>: [WebDriverAgentR:3018] SyscallError: setpriority(PRIO_DARWIN_ROLE, 3018, 3): No such process
2019-09-28 15:06:35:505 [IOSDeviceLog] Sep 28 15:06:35 itounozomunoiPad WebDriverAgentRunner-Runner(XCTest)[3018] <Error>: Exiting due to IDE disconnection.
2019-09-28 15:06:35:505 [IOSDeviceLog] Sep 28 15:06:35 itounozomunoiPad mobilewatchdog[60] <Notice>: 109103885427291: id=@ pid=300154224, state=3018
2019-09-28 15:06:35:507 [IOSDeviceLog] Sep 28 15:06:35 itounozomunoiPad assertiond[58] <Notice>: [WebDriverAgentR:3018] Port death watcher fired.
```

The cause is the disconnection of xcodebuiold

**Comment by KazuCocoa** [comment]
This happens only when `useNewWDA: false`. It uninstalls WDA from the device before starting WDA process.
https://github.com/appium/appium-xcuitest-driver/blob/b06738233f12d71ddbaba9418dfbf394c34af449/lib/driver.js#L510

So, I guess xcodebuild remains in the port.

**Comment by KazuCocoa** [comment]
The root cause is xcodebuild process.

When `useNewWDA: false`, appium tries to re-use running WDA if it is possible
[here](https://github.com/appium/appium-xcuitest-driver/blob/01a848bd169ee59c8a82909926a8e61776154f9a/lib/driver.js#L504-L509) 's `await this.wda.setupCaching();`. Then, Appium does not re-launch xcodebuild process.

Disconnection addressed in https://github.com/Magic-Pod/AppiumRegressionCheck/issues/26#issuecomment-536162321 happened after sending [create a new session to WDA](https://github.com/appium/appium-xcuitest-driver/blob/01a848bd169ee59c8a82909926a8e61776154f9a/lib/driver.js#L950-L954).
I predict the disconnection was something happened in xcodebuild which was out of Appium control since Appium simply sent the create session request and `status` request to check if WDA started.

Why create sessions with different port worked => Appium must re-create new xcodebuild process to WDA because WDA must communicate with the port which is not the same as the previous port. Then, xcodebuild launches again. The situation is the same as `useNewWDA` ture.

**Comment by NozomiIto** [comment]
Thanks for the investigation!!
It is difficult to resolve this problem on Appium side, right?
I found I can avoid this problem by useNewWDA for the first test run after Appium server start, so I will adopt this solution.

**Comment by KazuCocoa** [comment]
Yes, unfortunately. > appium side

**Comment by NozomiIto** [comment]
Thanks, then I mark this issue as resolved.

**Comment by NozomiIto** [comment]
I found this problem does not happen with Appium 1.17 anymore.
