### ISSUE TITLE
"Failed to parse APK file" happens for some Android real device with Appium 1.15.0

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#27]
- Happens with Appium 1.15.0 + Android real device (Android9, HUAWEI P20 lite)
- Does not happen with Appium 1.14.0 + Android real device (Android9, HUAWEI P20 lite)
- Also did not happen with Appium 1.15.0-rc4 + old Android real device (maybe Android6, HUAWEI)

## How to reproduce

`npm test -- --grep "should work with Android real device with Java8: a"`

## Failure log

```
nozomi-ito001:AppiumRegressionCheck itonozomi$ npm test -- --grep "should work with Android real device with Java8: a"

> appium_regression_check@0.0.1 test /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck
> mocha "--grep" "should work with Android real device with Java8: a"



  Appium
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
    simpleCheck
{"message":"[quit()] Unexpected data in simpleCallback.","data":"The URL '/wd/hub/session' did not map to a valid resource"}
      1) should work with Android real device with Java8: app=/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../test_app/ApiDemos-debug.apk
(node:28846) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
kill Appium server
killed Appium server
kill Appium server
killed Appium server


  0 passing (22s)
  1 failing

  1) Appium
       simpleCheck
         should work with Android real device with Java8: app=/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../test_app/ApiDemos-debug.apk:
     Error: [init({"platformName":"Android","deviceName":"Android","automationName":"uiautomator2","udid":"CHR7N18A22001624","appWaitActivity":"*","unicodeKeyboard":true,"resetKeyboard":true,"app":"/Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/test/../test_app/ApiDemos-debug.apk"})] The environment you requested was unavailable.
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk' exited with code 255'; Stderr: 'Error: Failed to parse APK file: /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk

Exception occurred while executing:
java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:360)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:929)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:166)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23669)
	at android.os.Binder.shellCommand(Binder.java:642)
	at android.os.Binder.onTransact(Binder.java:540)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2804)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4433)
	at com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:432)
	at android.os.Binder.execTransact(Binder.java:739)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk
	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1781)
	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1766)
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:353)
	... 10 more'; Code: '255'
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/webdriver.js:149:15
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:448:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:448:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at IncomingMessage.EventEmitter.emit (domain.js:448:20)
      at endReadableNT (_stream_readable.js:1129:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

npm ERR! Test failed.  See above for more details.
```

### APK

https://github.com/Magic-Pod/AppiumRegressionCheck/blob/master/test_app/ApiDemos-debug.apk

I think this id standard one.

## Appium log for failure with Appium 1.15.0

[log](https://gist.github.com/NozomiIto/a13d428c31c34b6ac548da1ca935c41d)

## Appium log for success with Appium 1.14.2

[log](https://gist.github.com/NozomiIto/3458423e64051cf866bee5c55c51c176)

**Comment by KazuCocoa** [comment]
Worked on Nokia Android 9 device with Appium 1.15.0.
What about adding `remoteAppsCacheLimit: 0` in the capability?

**Comment by KazuCocoa** [comment]
btw, can you succeed `/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk` by manual on the device?

**Comment by NozomiIto** [comment]
Set remoteAppsCacheLimit: 0 => Then worked! => Then I removed remoteAppsCacheLimit but it continues to work => Then I uninstalled everything (such as AppiumSetting app, Android API demo app, uiautomator2server) from the device => Then test begins to fail again with the same error unless specifying remoteAppsCacheLimit:0

**Comment by NozomiIto** [comment]
When the test failed, I tried direct ADB call and the result was the following.

```
nozomi-ito001:AppiumRegressionCheck itonozomi$ /Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk
Error: Failed to parse APK file: /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk

Exception occurred while executing:
java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:360)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:929)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:166)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23669)
	at android.os.Binder.shellCommand(Binder.java:642)
	at android.os.Binder.onTransact(Binder.java:540)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2804)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4433)
	at com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:432)
	at android.os.Binder.execTransact(Binder.java:739)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk
	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1781)
	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1766)
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:353)
	... 10 more
```

**Comment by KazuCocoa** [comment]
mm, I guess adb command failed to upload the apk to the device...
The logic has been changed in 1.14.0 (maybe) to upload the apk => install it instead of install apk directly from the host machine.

We simply use adb command so the behaviour depends on the installed adb tho.
mm

**Comment by KazuCocoa** [comment]
>  Then test begins to fail again with the same error unless specifying remoteAppsCacheLimit:0

I assume the 2nd time succeeded to upload the apk.
Appium handles if the test app upload&install again with checking the md5 on the device.
The app md5 is used as the app name on the test device.

**Comment by NozomiIto** [comment]
The error is due to APK format and this may happen on Android6 HUAWEI too if I remove the already installed APK. I will try tomorrow.

**Comment by KazuCocoa** [comment]
One possibility is some customised Android such as Chinese phones have issues in adb command.
Then, adb push => install it fails because of adb push was wrong, meanwhile adb install succeed.

But `remoteAppsCacheLimit: 0` simply removes existing apks from the device.
The steps ' adb push => install it' does not change.

hm...

**Comment by NozomiIto** [comment]
> The error is due to APK format and this may happen on Android6 HUAWEI too if I remove the already installed APK. I will try tomorrow.

I removed the all existing data from Android6 HUAWEI but it still worked. So it does not happen for the device with` Android 6` and `Device API level 23` even for the same APK.

**Comment by NozomiIto** [comment]
This did not happen for Sonly Xperia Andorid8.0.0 too.

- HUAWEI Android6 => OK
- Xperia Android8 => OK
- HUAWEI Android9 => NG

The apk is always the same.

**Comment by KazuCocoa** [comment]
Can you run `adb install` from your local without push => install it step?

I mean 
`/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 install -g /path/to/your/apk`

If it works, maybe we can propose to fallback or add the way in a capability.

**Comment by NozomiIto** [comment]
After  `/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk` caused `java.lang.IllegalArgumentException: Error: Failed to parse APK file`, I retrieved 3d97225b036c28750562ef8962defee6b1af19a4.apk by `adb pull /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk /Users/itonozomi/Desktop/`.

[3d97225b036c28750562ef8962defee6b1af19a4.apk.zip](https://github.com/Magic-Pod/AppiumRegressionCheck/files/3660559/3d97225b036c28750562ef8962defee6b1af19a4.apk.zip)

I found I couldn't expand this apk even after renaming extension to zip. This seems to be broken...

**Comment by KazuCocoa** [comment]
hm, okay.
Maybe `adb push` does not work in some devices.

**Comment by NozomiIto** [comment]
`/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 install -g /Users/itonozomi/Desktop/magicPod/ApiDemos-debug.apk`  => this worked despite `shell pm install -g /data/local/tmp/...` fails.

**Comment by NozomiIto** [comment]
> If it works with direct installation, we can propose it as a fallback plan (or as a caps)

Thanks! If necessary, I can report this problem to Appium issue list.

**Comment by NozomiIto** [comment]
- This did not happen with Appium1.14.2. I wonder which change caused this problem.
- Also I wonder why `remoteAppsCacheLimit: 0` resolves the problem.
- Also, I need a workaround without requiring users additional parameter set up. Do you think I can safely use `remoteAppsCacheLimit: 0` for all devices?

**Comment by KazuCocoa** [comment]
But an interesting story is https://github.com/appium/appium-adb/pull/423
Internally, the install command does push and install.
https://android.googlesource.com/platform/tools/base/+/master/ddmlib/src/main/java/com/android/ddmlib/Device.java#879

**Comment by KazuCocoa** [comment]
The cache has been introduced in 1.13.
So, one possibility is another issue is there between 1.14 and 1.15

**Comment by KazuCocoa** [comment]
Need to take a look at the cause more

**Comment by NozomiIto** [comment]
Main part of failure log:

```
2019-09-26 15:52:53:913 [ADB] Starting '/Users/itonozomi/Library/Android/sdk/tools/bin/apkanalyzer' with args ["manifest","print","/Users/itonozomi/.nodebrew/node/v10.16.0/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk"]
2019-09-26 15:52:55:266 [ADB] The installed 'io.appium.settings' package is older than '/Users/itonozomi/.nodebrew/node/v10.16.0/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' (18 < 19 or '2.14.1' < '2.14.2')'
2019-09-26 15:52:55:266 [ADB] Executing upgrade of '/Users/itonozomi/.nodebrew/node/v10.16.0/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
2019-09-26 15:52:55:280 [ADB] Running '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
2019-09-26 15:52:55:352 [ADB] The count of applications in the cache: 10
2019-09-26 15:52:55:352 [ADB] The application at '/Users/itonozomi/.nodebrew/node/v10.16.0/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' is already cached to '/data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk'
2019-09-26 15:52:55:354 [ADB] Running '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell pm install -r -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk'
2019-09-26 15:52:55:449 [ADB] Cannot install/upgrade 'io.appium.settings' because of 'Error executing adbExec. Original error: 'Command '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell pm install -r -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk' exited with code 255'; Stderr: 'Error: Failed to parse APK file: /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk
2019-09-26 15:52:55:449 [ADB] 
```

It seems settings_apk-debug.apk could not be installed.

**Comment by NozomiIto** [comment]
> Need to take a look at the cause more

I appreciate if you take a look. I think there exists other cause.

**Comment by NozomiIto** [comment]
Command used in Appium 1.15.0 is:

`/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell pm install -r -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk`

On the other hand the one used in Appium1.14.2 is:

`/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell pm install -g /data/local/tmp/appium_cache/12bb63270ecd4315cfaaa8d8202b809bbfccca11.apk`

Difference is `-r` option.

**Comment by KazuCocoa** [comment]
It replaces the existing app.
If nothing exists in the device, it does affect.

**Comment by NozomiIto** [comment]
Seems not related to this problem.

**Comment by NozomiIto** [comment]
3d97225b036c28750562ef8962defee6b1af19a4.apk => pm install succeeds for this APK.

[3d97225b036c28750562ef8962defee6b1af19a4.apk.zip](https://github.com/Magic-Pod/AppiumRegressionCheck/files/3665624/3d97225b036c28750562ef8962defee6b1af19a4.apk.zip)


12bb63270ecd4315cfaaa8d8202b809bbfccca11.apk => pm install fails for this APK.

[12bb63270ecd4315cfaaa8d8202b809bbfccca11.apk.zip](https://github.com/Magic-Pod/AppiumRegressionCheck/files/3665625/12bb63270ecd4315cfaaa8d8202b809bbfccca11.apk.zip)

**Comment by NozomiIto** [comment]
[Appium log when Appium settings app does not exist on the device](https://gist.github.com/NozomiIto/1f12ce3b8097cbe1bd08be8626214fbd).

This is a little different from [log for when Appium settings app already exists](https://gist.github.com/NozomiIto/a13d428c31c34b6ac548da1ca935c41d)

**Comment by NozomiIto** [comment]
```
2019-09-29 00:18:02:149 [ADB] 'io.appium.settings' is not installed
2019-09-29 00:18:02:149 [ADB] App '/Users/itonozomi/.nodebrew/node/v10.16.0/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' is not installed
2019-09-29 00:18:02:150 [ADB] Installing '/Users/itonozomi/.nodebrew/node/v10.16.0/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
2019-09-29 00:18:02:155 [ADB] Running '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
2019-09-29 00:18:02:213 [ADB] The count of applications in the cache: 10
2019-09-29 00:18:02:213 [ADB] The application at '/Users/itonozomi/.nodebrew/node/v10.16.0/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' is already cached to '/data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk'
2019-09-29 00:18:02:215 [ADB] Running '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk'
2019-09-29 00:18:02:305 [UiAutomator2] Deleting UiAutomator2 session
2019-09-29 00:18:02:307 [ADB] Running '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell am force-stop io.appium.android.apis'
2019-09-29 00:18:02:417 [ADB] Removing forwarded port socket connection: 8200 
2019-09-29 00:18:02:417 [ADB] Running '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 forward --remove tcp\:8200'
2019-09-29 00:18:02:448 [UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
2019-09-29 00:18:02:448 [UiAutomator2] Restoring hidden api policy to the device default configuration
2019-09-29 00:18:02:449 [ADB] Running '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell settings delete global hidden_api_policy_pre_p_apps'
2019-09-29 00:18:02:527 [ADB] Running '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell settings delete global hidden_api_policy_p_apps'
2019-09-29 00:18:02:603 [ADB] Running '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell settings delete global hidden_api_policy'
2019-09-29 00:18:02:690 [BaseDriver] Event 'newSessionStarted' logged at 1569683882689 (00:18:02 GMT+0900 (GMT+09:00))
2019-09-29 00:18:02:691 [MJSONWP] Encountered internal error running command: Error executing adbExec. Original error: 'Command '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s CHR7N18A22001624 shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk' exited with code 255'; Stderr: 'Error: Failed to parse APK file: /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk
2019-09-29 00:18:02:691 [MJSONWP] 
2019-09-29 00:18:02:692 [MJSONWP] Exception occurred while executing:
2019-09-29 00:18:02:692 [MJSONWP] java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk
2
```

**Comment by KazuCocoa** [comment]
Were https://github.com/Magic-Pod/AppiumRegressionCheck/issues/27#issuecomment-536197613 the same apk? (And I think they are opposite since apk analyzer by AndroidStudio cannot analyse 3d97225b036c28750562ef8962defee6b1af19a4.apk.zip )
Their size is different.  3d97225b03 is smaller than 12bb63270

**Comment by NozomiIto** [comment]
According to log ( https://gist.github.com/NozomiIto/a13d428c31c34b6ac548da1ca935c41d and https://gist.github.com/NozomiIto/3458423e64051cf866bee5c55c51c176 ), both are for `io.appium.settings/apks/settings_apk-debug.apk`.

- The one is for Appium1.14.2, the other is for Appium 1.15.0
- I couldn't expand both by zip unarchiver, but even so, I can install Appium1.14.2 setting app by `pm install` but can't install Appium 1.15.0 setting.

**Comment by NozomiIto** [comment]
```
nozomi-ito001:AppiumRegressionCheck itonozomi$ adb install /Users/itonozomi/Desktop/12bb63270ecd4315cfaaa8d8202b809bbfccca11.apk
Success
nozomi-ito001:AppiumRegressionCheck itonozomi$ adb install /Users/itonozomi/Desktop/3d97225b036c28750562ef8962defee6b1af19a4.apk
adb: failed to install /Users/itonozomi/Desktop/3d97225b036c28750562ef8962defee6b1af19a4.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl1013028913.tmp/base.apk]
```

**Comment by KazuCocoa** [comment]
Can you fined a log like `Collecting the destination apk`?

- https://github.com/appium/appium-support/pull/122/files
- https://github.com/appium/appium-adb/blob/c12a23c6ead3a1b1605e55b394193bd5c53aaff8/lib/tools/android-manifest.js#L305

If the zip is wrong, here is potential cause

**Comment by NozomiIto** [comment]
Both success log and failure log ( https://gist.github.com/NozomiIto/a13d428c31c34b6ac548da1ca935c41d and https://gist.github.com/NozomiIto/3458423e64051cf866bee5c55c51c176 ) don't include such message.

**Comment by NozomiIto** [comment]
I tried direct install from node_modules/io.appium.settings but even it failed.

```
nozomi-ito001:28.0.3 itonozomi$ adb  install /Users/itonozomi/magicpod/node/src/magic_pod_client/src/desktop-main/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk
adb: failed to install /Users/itonozomi/magicpod/node/src/magic_pod_client/src/desktop-main/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package io.appium.settings signatures do not match previously installed version; ignoring!]
```

I use io.appium.settings@2.14.2

**Comment by NozomiIto** [comment]
Ah, sorry, this worked.

```
nozomi-ito001:28.0.3 itonozomi$ adb  install /Users/itonozomi/magicpod/node/src/magic_pod_client/src/desktop-main/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk
Success
```

io.appium.settings@2.14.2

**Comment by NozomiIto** [comment]
[cacheApk](https://github.com/appium/appium-adb/blob/v7.13.0/lib/tools/apk-utils.js#L508) makes the target APK can make broken? I'm not sure.. 
All I can do now is, always specifying `remoteAppsCacheLimit: 0`. I assume this won't make the test launch critically slow.

**Comment by KazuCocoa** [comment]
Not sure to be honest since the logic simply removes all of the existing apks in the device.
Appium usually does `am push` and `am install` to install apks regardless of remoteAppsCacheLimit.

The logic, `am push` and `am install` it, looks the same as `adb install` does in the logic. So, potentially, they are the same.
But probably `am push` leads the error.

--

note:

We probably can propose a retry logic when the installation fails.
It means re-push and installs it again after the failure.

**Comment by NozomiIto** [comment]
Mark as resolved.

**Comment by devenbhatt007** [comment]
> Ah, sorry, this worked.

This is working.

Thanks, man.

**Comment by surajl11** [comment]
where can I set remoteAppsCacheLimit: 0  please help
