### ISSUE TITLE
mobile: scroll test fails with Appium 1.17.0rc

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#31]
- `npm install` in this directory
- `npm test -- --grep "mobile: scroll should work on iOS simulator13"`

```
     Error: [execute("mobile: scroll",{"element":{"ELEMENT":"22000000-0000-0000-9F0F-010000000000"},"toVisible":true})] Error response status: 12, , InvalidElementState - An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element). Selenium error: Error Domain=com.facebook.WebDriverAgent Code=1 "Failed to find scrollable visible parent with 2 visible children" UserInfo={NSLocalizedDescription=Failed to find scrollable visible parent with 2 visible children}
      at exports.newError (node_modules/wd/lib/utils.js:152:13)
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/callbacks.js:94:19
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/webdriver.js:196:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:475:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:475:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at IncomingMessage.EventEmitter.emit (domain.js:475:20)
      at endReadableNT (_stream_readable.js:1184:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Appium log

https://gist.github.com/NozomiIto/b67f530d8ef2e4ee4ad768f5b9153fb3

- The element is outside of the screen.
- It worked with appium1.16.0, I think

**Comment by NozomiIto** [comment]
<img width="360" alt="Screen Shot 2020-03-05 at 10 31 39" src="https://user-images.githubusercontent.com/4276719/75939018-84a58200-5ecc-11ea-9e48-bb7d49b05480.png">

<img width="365" alt="Screen Shot 2020-03-05 at 10 31 04" src="https://user-images.githubusercontent.com/4276719/75939029-896a3600-5ecc-11ea-8fb3-319919ce820f.png">

**Comment by NozomiIto** [comment]
Close since it happens on Appium1.16.0 too. Maybe this is Xcode issue.
